---
permalink: deploy/download-ontap-tools.html 
sidebar: sidebar 
keywords:  
summary: Sie können die .ova-Datei für ONTAP-Tools für VMware vSphere von der NetApp Support-Website herunterladen. 
---
= Laden Sie ONTAP Tools für VMware vSphere herunter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `.zip` Datei, die Binärdateien (_.ova_) und signierte Zertifikate für ONTAP-Tools für VMware vSphere enthält, von der herunterladen https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["NetApp Support-Website"^].

Nach Abschluss der Implementierung werden die ONTAP Tools für VMware vSphere und VASA-Produkte in Ihrer Umgebung installiert. ONTAP Tools für VMware vSphere funktionieren standardmäßig, sobald Sie das Implementierungsmodell ausgewählt haben und anhand Ihrer Anforderungen auswählen, ob VASA Provider aktiviert werden soll. Weitere Informationen finden Sie unter link:../configure/registration-process.html["Registrieren Sie den VASA Provider mit einer vCenter Server-Instanz"] .



== Content Library

Eine Content-Bibliothek in VMware ist ein Container-Objekt, das VM-Vorlagen, vApp-Vorlagen und andere Dateitypen speichert. Die Bereitstellung mit Inhaltsbibliothek bietet Ihnen eine nahtlose Erfahrung, da sie nicht von der Netzwerkkonnektivität abhängt.


NOTE: Sie sollten die Inhaltsbibliothek auf einem freigegebenen Datastore speichern, sodass alle Hosts in einem Cluster darauf zugreifen können. Sie müssen eine Inhaltsbibliothek erstellen, um die OVA zu speichern, bevor Sie die OVA in der HA-Konfiguration bereitstellen. Erstellen Sie die Inhaltsbibliothek mithilfe der folgenden Schritte:

*Schritte*

. Melden Sie sich mit beim vSphere-Client an `\https://vcenterip/ui`
. Wählen Sie die horizontalen Ellipsen neben vSphere Client aus und wählen Sie *Content Library*.
. Wählen Sie auf der rechten Seite die Option *Erstellen*.
. Geben Sie einen Namen für die Bibliothek ein, und erstellen Sie die Inhaltsbibliothek.
. Navigieren Sie zu der von Ihnen erstellten Inhaltsbibliothek.
. Wählen Sie *actions* rechts auf der Seite aus und wählen Sie *Import item* und importieren Sie die OVA-Datei.

