---
permalink: protect/update-credentials.html 
sidebar: sidebar 
keywords: SRA credentials, updating 
summary: Damit SRM mit SRA kommunizieren kann, sollten Sie die SRA-Anmeldedaten auf dem SRM-Server aktualisieren, wenn Sie die Anmeldedaten geändert haben. 
---
= SRA-Anmeldedaten aktualisieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Damit SRM mit SRA kommunizieren kann, sollten Sie die SRA-Anmeldedaten auf dem SRM-Server aktualisieren, wenn Sie die Anmeldedaten geändert haben.

*Was Sie brauchen*

Sie sollten die im Thema genannten Schritte ausgeführt haben link:../protect/configure-on-srm-appliance.html["Konfigurieren von SRA auf der SRM-Appliance"].

*Schritte*

. Führen Sie die folgenden Befehle aus, um das Kennwort für den im Cache gespeicherten ONTAP-Werkzeugordner des SRM-Computers zu löschen:
+
.. `sudo su <enter root password>`
.. `docker ps`
.. `docker exec -it <container_id> sh`
.. `cd /conf`
.. `rm -rf *`


. Führen Sie den Perl-Befehl aus, um SRA mit den neuen Anmeldeinformationen zu konfigurieren:
+
.. `cd ..`
.. `perl command.pl -I --otv-ip <OTV_IP>:8443 --otv-username <OTV_ADMIN_USERNAME> --otv-password <OTV_ADMIN_PASSWORD> --vcenter-guid <VCENTER_GUID>` Sie benötigen ein einziges Angebot um den Passwortwert herum.
+
Eine Erfolgsmeldung, die bestätigt, dass die Speicher-Anmeldedaten gespeichert werden, wird angezeigt. SRA kann mit dem SRA-Server unter Verwendung der angegebenen IP-Adresse, des Ports und der Anmeldeinformationen kommunizieren.




