---
permalink: automation/mount-unmount-workflow.html 
sidebar: sidebar 
keywords: REST APIs, swagger 
summary: 'Sie können einen VMware Virtual Volumes (VVols)-Datastore auf einen oder mehrere zusätzliche Hosts mounten, um zusätzlichen Hosts den Storage-Zugriff zu ermöglichen. Sie können VVols-Datastore mithilfe von APIs abmounten.' 
---
= Mounten und unmounten Sie einen VVols Datastore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen VMware Virtual Volumes (VVols)-Datastore auf einen oder mehrere zusätzliche Hosts mounten, um zusätzlichen Hosts den Storage-Zugriff zu ermöglichen. Sie können VVols-Datastore mithilfe von APIs abmounten.

Verwenden Sie die folgende API, um einen VVols Datastore zu mounten oder abzuhängen. Sie müssen x-auth für die API übergeben. Sie können diese X-Auth aus der neuen API generieren, die unter Auth in Swagger hinzugefügt wurde.

[listing]
----
/virtualization/api/v1/auth/vcenter-login
----
[listing]
----
PATCH
/virtualization/api/v1/vcenters/{vcguid}/vvols/datastores/{moref}/hosts
----
Erhalten Sie den vVol Datastore moref von vCenter.

Text Anfordern

[listing]
----
{
  "operation": "mount",
  "morefs": [
    "host-7044"
  ],
}
----
Beispiele: * Montage auf zusätzlichem Host

Verwenden Sie die folgende API, um auf zusätzlichen Host zu mounten:

[listing]
----
/api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores/datastore-24/hosts

     Request Body
     {
      "operation": "mount",
      "morefs": ["host-13"],
     }
----
* Unmounten auf zusätzlichem Host


Verwenden Sie die folgende API, um die Bereitstellung auf einem zusätzlichen Host aufzuheben:

[listing]
----
/api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores/datastore-24/hosts

     Request Body
     {
      "operation": "unmount",
      "morefs": ["host-13"],
     }
----