---
permalink: configure/add-vcenter.html 
sidebar: sidebar 
keywords:  
summary: 'VCenter Server-Instanzen sind die zentralen Management-Plattformen zur Steuerung von Hosts, Virtual Machines (VM) und Storage-Back-Ends.' 
---
= Fügen Sie vCenter Server-Instanzen hinzu und verwalten Sie sie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VCenter Server stellt die zentrale Managementplattform bereit, mit der Sie Hosts, Virtual Machines (VMs) und Storage-Back-Ends steuern können.



== Fügen Sie eine vCenter Server-Instanz hinzu

*Über diese Aufgabe*

Sie können mehrere vCenter Server-Instanzen mit einer Instanz von ONTAP-Tools für VMware vSphere hinzufügen und managen.

*Schritte*

. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://loadBalanceIP:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie in der Seitenleiste *vCenters* aus.
. Wählen Sie *Add* für die Instanzen des vCenter-Servers aus und geben Sie Ihre vCenter-IP-Adresse/den Hostnamen, den Benutzernamen, das Kennwort und die Portdetails an.


Wenn Sie ONTAP Tools eine vCenter Server-Instanz hinzufügen, werden die folgenden Aktionen automatisch ausgeführt:

* Das vCenter Client-Plug-in ist registriert
* Benutzerdefinierte Berechtigungen für die Plug-ins und APIs werden an die vCenter Server Instanz übertragen
* Zum Verwalten der Benutzer werden benutzerdefinierte Rollen erstellt.




== Registrieren Sie ONTAP-Tools für das VMware vSphere Plug-in mit vCenter Server-Instanz

Wenn Sie eine vCenter Server-Instanz hinzufügen, werden ONTAP-Tools für VMware vSphere-Plug-in automatisch als Remote-Plug-in für vCenter Server registriert. Das Plug-in ist auf den vSphere-Benutzeroberflächen-Shortcuts sichtbar.

Das Plug-in wird mit einem Schlüssel _com.netapp.otv_ für die vCenter Server Instanz registriert und ist im ExtensionManager der vCenter Server Instanz zu sehen.



== Heben Sie die Registrierung von ONTAP Tools für das VMware vSphere Plug-in auf

Sie können die ONTAP-Tools für das VMware vSphere Plug-in mithilfe der folgenden Schritte von einer vCenter Server-Instanz abmelden.

*Schritte*

. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://loadBalanceIP:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie in der Seitenleiste vCenter aus.
. Klicken Sie auf die vertikalen Ellipsen gegenüber dem vCenter, das Sie entfernen möchten, und wählen Sie die Option *Entfernen* aus.
+

NOTE: Sie können eine vCenter Server-Instanz nicht entfernen, wenn eine Speicherzuweisung mit ihr verbunden ist. Sie müssen die Zuordnung entfernen, bevor Sie die vCenter Server-Instanz entfernen.



Wenn Sie vCenter Server-Instanzen in ONTAP-Tools entfernen, werden die folgenden Aktionen automatisch ausgeführt:

* Die Registrierung des Plug-ins wurde aufgehoben.
* Plug-in-Berechtigungen und Plug-in-Rollen werden entfernt.

