---
permalink: configure/create-vvols-datastore.html 
sidebar: sidebar 
keywords:  
summary: Sie können einen VVols-Datastore mit neuen Volumes oder mit vorhandenen Volumes erstellen. Zudem ist es möglich, einen VVols-Datastore mit einer Kombination aus vorhandenen Volumes und neuen Volumes zu erstellen. 
---
= Erstellen eines Datenspeichers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie einen Datastore auf Host-Cluster-Ebene erstellen, wird der Datastore auf allen Hosts des Ziels erstellt und gemountet. Die Aktion wird nur aktiviert, wenn der aktuelle Benutzer über die Berechtigung zur Ausführung verfügt.

Der Assistent „Datastore erstellen“ unterstützt die Erstellung von NFS-, VMFS- und VVols-Datenspeichern.



== Erstellen Sie einen VVols-Datastore

Sie können einen VVols-Datastore entweder mit neuen Volumes oder mit vorhandenen Volumes erstellen. Sie können keinen VVols-Datastore mit einer Kombination aus vorhandenen und neuen Volumes erstellen.


NOTE: Überprüfen Sie, ob die Root-Aggregate nicht der SVM zugeordnet sind.

.Bevor Sie beginnen
Stellen Sie sicher, dass der VASA-Anbieter beim ausgewählten vCenter registriert ist.

.Schritte
. Melden Sie sich mit beim vSphere-Client an `\https://vcenterip/ui`
. Klicken Sie mit der rechten Maustaste auf ein Hostsystem oder einen Hostcluster oder ein Rechenzentrum, und wählen Sie dann *NetApp ONTAP Tools* > *Datastore erstellen* aus.
. Wählen Sie im Bereich *Typ* unter *Datastore Type* die Option VVols aus.
. Geben Sie im Bereich *Name und Protokoll* die Informationen *Datastore Name* und *Protocol* an.
. Wählen Sie im Bereich *Storage* *Platform* und *Storage VM* aus. Wählen Sie im Abschnitt *Erweiterte Optionen* die Option Benutzerdefinierte Exportrichtlinie (für NFS-Protokoll) oder benutzerdefinierten Initiatorgruppennamen (für iSCSI-Protokoll) aus.
+
** Mit Plattform- und asymmetrischen Optionen können Sie die Dropdown-Optionen für SVMs herausfiltern. Sie sollten die SVM auswählen, die erstellt werden soll, oder die Volumes für die Datastore-Erstellung verwenden.
** Die Umschalttaste *Asymmetric* ist nur sichtbar, wenn iSCSI im vorherigen Schritt ausgewählt wurde und Leistung oder Kapazität im Dropdown-Menü Plattform ausgewählt ist.
** Wählen Sie die Schaltfläche *Asymmetric* für die AFF-Plattform und deaktivieren Sie sie für die ASA-Plattform.


. Im Bereich *Speicherattribute* können Sie entweder neue Volumes erstellen oder die vorhandenen Volumes verwenden. Beim Erstellen eines neuen Volumes können Sie die QoS auf dem Datastore aktivieren.
. Überprüfen Sie Ihre Auswahl im Fenster *Zusammenfassung* und klicken Sie auf *Fertig stellen*. Der VVols Datastore wird auf allen Hosts erstellt und gemountet.




== Erstellen Sie einen NFS-Datastore

Ein Datastore des VMware Network File System (NFS) verwendet das NFS-Protokoll, um ESXi-Hosts über ein Netzwerk mit einem Shared Storage-Gerät zu verbinden. NFS-Datastores werden häufig in VMware vSphere Umgebungen verwendet und bieten verschiedene Vorteile, z. B. Einfachheit und Flexibilität.

.Schritte
. Melden Sie sich mit beim vSphere-Client an `\https://vcenterip/ui`
. Klicken Sie mit der rechten Maustaste auf ein Hostsystem oder einen Hostcluster oder ein Rechenzentrum, und wählen Sie dann *NetApp ONTAP Tools* > *Datastore erstellen* aus.
. Wählen Sie im Bereich *Typ* NFS unter *Datastore Type* aus.
. Geben Sie im Bereich *Name und Protokoll* den Namen, die Größe und die Protokollinformationen des Datastore ein. Wählen Sie in den erweiterten Optionen *Datastore Cluster* und *Kerberos Authentication* aus.
+

NOTE: Kerberos-Authentifizierung ist nur verfügbar, wenn das NFS 4.1-Protokoll ausgewählt ist.

. Wählen Sie im Bereich *Storage* *Platform* und *Storage VM* aus. Sie können *Custom Export Policy* im Abschnitt *Advanced Option* auswählen.
+
** *Asymmetric* Umschalttaste ist nur sichtbar, wenn Leistung oder Kapazität im Dropdown-Menü Plattform ausgewählt ist.
** *Any* Option in der Plattform-Dropdown ermöglicht es Ihnen, alle SVMs zu sehen, die Teil des vCenter sind, unabhängig von der Plattform oder asymmetrischen Flagge.


. Wählen Sie im Bereich *Speicherattribute* das Aggregat für die Erstellung des Volumes aus. Wählen Sie in den erweiterten Optionen *Space Reserve* und *Enable QoS* je nach Bedarf.
. Überprüfen Sie die Auswahl im Fenster *Zusammenfassung* und klicken Sie auf *Fertig stellen*.


Der NFS-Datastore wird auf allen Hosts erstellt und gemountet.



== Erstellen Sie einen VMFS-Datastore

Virtual Machine File System (VMFS) ist ein geclustertes Filesystem, das speziell zum Speichern von VM-Dateien in VMware vSphere Umgebungen entwickelt wurde. Sie ermöglicht es mehreren ESXi-Hosts, gleichzeitig auf dieselben VM-Dateien zuzugreifen, was Funktionen wie vMotion und Hochverfügbarkeit ermöglicht.

.Schritte
. Melden Sie sich mit beim vSphere-Client an `\https://vcenterip/ui`
. Klicken Sie mit der rechten Maustaste auf ein Hostsystem oder einen Hostcluster oder einen Datastore, und wählen Sie dann *NetApp ONTAP Tools* > *Datastore erstellen* aus.
. Wählen Sie im Bereich *Typ* VMFS unter *Datastore Type* aus.
. Geben Sie im Bereich *Name und Protokoll* den Namen, die Größe und die Protokollinformationen des Datastore ein. Wählen Sie im Abschnitt *Erweiterte Optionen* des Teilfensters den Datastore-Cluster aus, dem Sie diesen Datastore hinzufügen möchten.
. Wählen Sie im Fensterbereich Storage die Option Platform and Storage VM aus. Wählen Sie die Schaltfläche Asymmetric Toggle. Geben Sie den *Custom Initiator Group Name* im Abschnitt *Advanced options* des Fensters ein (optional). Sie können entweder eine vorhandene Initiatorgruppe für den Datastore auswählen oder eine neue Initiatorgruppe mit einem benutzerdefinierten Namen erstellen.
+
Wenn Sie die Option *any* in der Dropdown-Liste der Plattform wählen, sehen Sie alle SVMs, die Teil des vCenter sind, unabhängig von der Plattform oder dem asymmetrischen Flag.

. Wählen Sie im Bereich Speicherattribute aus dem Dropdown-Menü die Option *Aggregat* aus. Wählen Sie im Abschnitt *Erweiterte Optionen* die Optionen *Platzreserve*, *vorhandenes Volume verwenden* und *QoS* aktivieren aus und geben Sie die erforderlichen Details an.
. Überprüfen Sie die Datastore-Details im Bereich *Summary* und klicken Sie auf *Finish*. Der VMFS Datastore wird auf allen Hosts erstellt und gemountet.

